# 配置服务器端口
server:
  port: 80

# 配置数据库参数
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis_db
    username: root
    password: leesin
    # 配置使用阿里连接池
    type: com.alibaba.druid.pool.DruidDataSource

# 配置全局日志级别
logging:
  level:
    root: info

# 配置 mybatis-plus 的日志实现
mybatis-plus:
  configuration:
    # 指定 MyBatis-Plus 的日志实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除对应的字段
      logic-delete-field: is_del
      # 逻辑删除字段值
      logic-delete-value: 1
      # 逻辑未删除字段值
      logic-not-delete-value: 0